---

language: c

matrix:
  include:
    - os: windows
      script:
        - echo "Windows"
    - os: linux
      dist: xenial
      complier:
        - gcc 
      addons:
        apt:
          packages:
            - openssl
            - valgrind
            - check
            - cppcheck
            - make
            - cmake
            - lcov
            - doxygen
            - help2man
            - clang-tidy
      script:
        - echo "UP"
        - gcc -std=c11 -g -ftest-coverage --coverage -Wall -Wextra -pedantic -o tests_mnemonics -I./src/ -I./tests/ src/errorcodes.h src/errorcodes.c src/dictionary.c src/dictionary.h src/mnemonics.h src/mnemonics.c tests/test_mnemonics.c -lcrypto -lcheck -lpthread -lm -lrt -lsubunit
        - ./tests_mnemonics
        - valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./tests_mnemonics
        - lcov --directory . --capture --output-file coverage.info
        - lcov --list coverage.info
        - cppcheck --error-exitcode=0 --enable=all --suppress=missingIncludeSystem ./src/*.c ./src/*.h
        - clang-tidy src/*.h src/*.c -checks=*

